name: Deploy DAGs to Composer

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: rock-baton-429320-m9
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Decode and Write Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/keyfile.json

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=/tmp/keyfile.json

      - name: Copy DAGs to GCS
        run: gsutil -m rsync -r dags/ gs://us-central1-webscrapperprop-9e78e2c1-bucket/dags/

      - name: Copy Plugins to GCS
        run: gsutil -m rsync -r plugins/ gs://us-central1-webscrapperprop-9e78e2c1-bucket/plugins/
